[windows]
54.160.53.18

[windows:vars]
ansible_user=ansible
ansible_password=C1r11@21949
ansible_port=5986
ansible_connection=winrm
ansible_winrm_transport=basic
ansible_winrm_server_cert_validation=ignore